/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registrationntv;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import static registrationntv.UserPage.encrypt;

/**
 *
 * @author gygsh
 */

public class AdminReport extends javax.swing.JFrame {
    Color red = new Color(255,102,102);
    Color green = new Color(153,255,51);
    /**
     * Creates new form UserHomeFinal
     */
    String RR;
     String FTName;
    String FTRegNo;
    String FTDateIssue;
    String FTDateExp;
    String FTIssueAuth;
    String FTAddr;
    String FvehicleClass;
    String FbodyType;
    String FmakerName;
    String FdoM;
    String FcC;
    String FMclass;
    String FengineNo;
    String FseatingCap;
    String Funladen;
    String Ffuel;
    String Freciept;
    String Ffee;
    String status;
    String RenewalNo;
    String RC,IC,EC,TC;
    String Final;
    public AdminReport() {
        initComponents();
        setLocationRelativeTo(null);
    }
     public AdminReport(String RenewalNumber) {
        initComponents();
        RR = RenewalNumber.toUpperCase();
        setLocationRelativeTo(null);
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextOne = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FinalRep = new javax.swing.JTextArea();
        View = new javax.swing.JButton();
        Validate = new javax.swing.JButton();
        ValidateT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextOne.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));
        jPanel3.setForeground(new java.awt.Color(255, 204, 102));

        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        jLabel2.setText("RENEWAL OF NON - TRANSPORT VEHICLES");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registrationntv/EmblemIcon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addGap(86, 86, 86)
                .addComponent(jLabel2)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(22, 22, 22))
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 102));
        jPanel4.setForeground(new java.awt.Color(255, 204, 102));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setText("MINISTRY OF ROAD TRANSPORT & HIGHWAYS");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("VAHAN CITIZEN SERVICE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabel15.setText("Final Report");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        FinalRep.setColumns(20);
        FinalRep.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        FinalRep.setRows(5);
        jScrollPane1.setViewportView(FinalRep);

        View.setBackground(new java.awt.Color(255, 204, 102));
        View.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        View.setText("VIEW");
        View.setBorder(null);
        View.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewMouseClicked(evt);
            }
        });

        Validate.setBackground(new java.awt.Color(255, 204, 102));
        Validate.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        Validate.setText("VALIDATE");
        Validate.setBorder(null);
        Validate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ValidateMouseClicked(evt);
            }
        });

        ValidateT.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        ValidateT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ValidateT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));

        javax.swing.GroupLayout TextOneLayout = new javax.swing.GroupLayout(TextOne);
        TextOne.setLayout(TextOneLayout);
        TextOneLayout.setHorizontalGroup(
            TextOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(TextOneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TextOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TextOneLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(View, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(461, 461, 461)
                        .addComponent(ValidateT, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Validate, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TextOneLayout.setVerticalGroup(
            TextOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TextOneLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(TextOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(TextOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(View, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(TextOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ValidateT)
                        .addComponent(Validate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewMouseClicked
        // TODO add your handling code here:
         try {
          
                 String url = "jdbc:h2:~/test";
                 Connection C = DriverManager.getConnection(url,"sa","sa");
                 String query = "SELECT * FROM NTVMAIN WHERE RRNO = '"+RR+"';";
                   Statement S = C.createStatement(); 
                   ResultSet RS = S.executeQuery(query);
                   
                    while(RS.next()) {
                        
                        FTRegNo = RS.getString("REGNO");
                        FTDateIssue = RS.getString("DATEISSUE");
                        FTDateExp = RS.getString("DATEEXP");
                        FTIssueAuth = RS.getString("ISSUEAUTH");
                        FTAddr = RS.getString("ADDR");
                        FvehicleClass = RS.getString("VEHICLECLASS");
                        FbodyType = RS.getString("BODYTYPE");
                        FmakerName = RS.getString("MAKERNAME");
                        FdoM = RS.getString("DOM");
                        FcC = RS.getString("CC");
                        FMclass = RS.getString("MCLASS");
                        FengineNo = RS.getString("ENGINENO");
                        FseatingCap = RS.getString("SEATCAP");
                        Funladen = RS.getString("UNLADEN");
                        Ffuel = RS.getString("FUEL");
                        Freciept = RS.getString("RECIEPT");
                        Ffee = RS.getString("FEE");
                    
                        RC = RS.getString("RC");
                        IC = RS.getString("IC");
                        EC = RS.getString("EC");
                        TC = RS.getString("TC");
                        status = RS.getString("STATUS");
                        
                       Final =  "1. REGISTRATION NUMBER : \t"+FTRegNo+"\n"+
                                "2. DATE OF ISSUE : \t"+FTDateIssue+"\n"+
                                "3. DATE OF EXPIRY : \t"+FTDateExp+"\n"+
                                "4. ISSUED AUTHORITY : \t"+FTIssueAuth+"\n"+
                                "5. PRESENT ADDRESS : \t"+FTAddr+"\n\n"+
                                "6. VEHICLE CLASS :  \t"+FvehicleClass+"\n"+
                                "7. BODY TYPE : \t"+FbodyType+"\n"+
                                "8. MAKER'S NAME : \t"+FmakerName+"\n"+
                                "9. DATE OF MFG : \t"+FdoM+"\n"+
                                "10.CC / HP : \t"+FcC+"\n"+
                                "11.MAKER'S CLASSIFICATION : \t" +FMclass+"\n"+
                                "12.ENGINE NUMBER : \t" +FengineNo+"\n"+
                                "13.SEATING CAPACITY : \t"+FseatingCap+"\n"+
                                "14. UNLADEN WEIGHT: \t"+Funladen+"\n"+
                                "15. FUEL CONSUMPTION : \t" +Ffuel+"\n"+"\n"+"PAYMENT & DOCUMENTATION DETAILS"+"\n\n"+
                                "16. FEE RECIEPT NUMBER :\t" +Freciept+"\n"+
                                "17. AMOUNT PAID (IN RS) :\t" +Ffee+"\n"+
                                
                                
                                 "18. REGISTRATION CERTIFICATE NUMBER : \t"+RC+"\n"+
                                 "19. INSURANCE CERTIFICATE NUMBER : \t"+IC+"\n"+
                                 "20. EMISSION CERTIFICATE NUMBER : \t"+EC+"\n"+
                                 "21. TAX CERTIFICATE NUMBER : \t"+TC;
                                
                                
                    FinalRep.setText(Final);
                    
            }
              S.close();
              RS.close();
        }catch(SQLException e) {
            System.out.println(e);
            showMessageDialog(this,"Error Registering \n Contact System Admininstrator","ALERT",JOptionPane.ERROR_MESSAGE);
            
        }

    }//GEN-LAST:event_ViewMouseClicked

    private void ValidateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ValidateMouseClicked
        // TODO add your handling code here:
        String A = ValidateT.getText().toUpperCase();
        String Query = new String() ;
        if(A.equals("APPROVE")){
            Query = "UPDATE NTVMAIN SET STATUS = 'A' WHERE RRNO = '"+RR+"';";
        } 
        else if(A.equals("REJECT")) {
             Query = "UPDATE NTVMAIN SET STATUS = 'R' WHERE RRNO = '"+RR+"';";
        }
     
       try {
                 String url = "jdbc:h2:~/test";
                Connection C = DriverManager.getConnection(url,"sa","sa");
                Statement S = C.createStatement();
                S.executeUpdate(Query);
                
                showMessageDialog(this,"\n Successfully Authorised! \n","SUCCESSFUL",JOptionPane.INFORMATION_MESSAGE);
                S.close();
                C.close();
                
                new AdminPage().setVisible(true);
                this.dispose();
                
            }catch(SQLException E) {
                System.out.println(E);
            }
            
    }//GEN-LAST:event_ValidateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea FinalRep;
    private javax.swing.JPanel TextOne;
    private javax.swing.JButton Validate;
    private javax.swing.JTextField ValidateT;
    private javax.swing.JButton View;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
