/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registrationntv;

import javax.swing.JOptionPane;

/**
 *
 * @author gygsh
 */
public class UserHome extends javax.swing.JFrame {

    /**
     * Creates new form UserHome
     */
    public UserHome() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    String[] verify =  {"Name","Registered Number","Date Of Issue","Date Of Expiry","Issuing Authority","Address","Confirmation"};
    
    
     public static String encrypt(String Key) {
	      char[] key = Key.toCharArray();
        for(int i = 0; i < key.length; i++) {
            switch(key[i]) {
                case 'a': {
                    key[i] = '!';
                    break;
                }
                 case 'e': {
                    key[i] = '#';
                    break;
                }
                 case 'i': {
                    key[i] = '%';
                    break;
                }
                 case 'o': {
                    key[i] = '&';
                    break;
                }
                 case 'u': {
                    key[i] = '(';
                    break;
                }
                 case '1': {
                    key[i] = 'i';
                    break;
                } case '2': {
                    key[i] = 'h';
                    break;
                } case '3': {
                    key[i] = 'g';
                    break;
                } case '4': {
                    key[i] = 'f';
                    break;
                } case '5': {
                    key[i] = 'e';
                    break;
                } case '6': {
                    key[i] = 'd';
                    break;
                } case '7': {
                    key[i] = 'c';
                    break;
                } case '8': {
                    key[i] = 'b';
                    break;
                } case '9': {
                    key[i] = 'a';
                    break;
                }case '0': {
                    key[i] = 'j';
                    break;
                }
                
                
            }
        }
        return String.valueOf(key);
    }
     
     int validateVerify() {
       int count = -1;
       if(Name.getText().equals("")) {
           count = 0;
          return count;
       }
       if(RegisterNo.getText().equals("")) {
           count = 1;
           return count;
       }
        if(DateIssue.getText().equals("")) {
            count = 2;
            return count;
        }
        if(DateExpiry.getText().equals("")) {
            count = 3;
            return count;
        }
        if(IssuingAuthority.getText().equals("")) {
            count = 4;
            return count;
        }
        if(Address.getText().equals("")) {
            count = 5;
            return count;
        }
        if(Confirm.isSelected() == false) { {
            count = 6;
            return count;
        }
        
        }
        if(count == -1) {
            return -1;
        }
        return count;
     }
        
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NewUserLink = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        RenewalSub = new javax.swing.JLabel();
        Confirm = new javax.swing.JCheckBox();
        NewUserLink2 = new javax.swing.JLabel();
        NewUserLink3 = new javax.swing.JLabel();
        NewUserLink4 = new javax.swing.JLabel();
        NewUserLink5 = new javax.swing.JLabel();
        NewUserLink6 = new javax.swing.JLabel();
        NewUserLink7 = new javax.swing.JLabel();
        IssuingAuthority = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        RegisterNo = new javax.swing.JTextField();
        DateIssue = new javax.swing.JTextField();
        DateExpiry = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Address = new javax.swing.JTextArea();
        NextBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        KM = new javax.swing.JLabel();

        jLabel10.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        jLabel10.setText("New User Portal");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));
        jPanel3.setForeground(new java.awt.Color(255, 204, 102));

        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        jLabel2.setText("RENEWAL OF NON - TRANSPORT VEHICLES");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\E-Governance\\RegistrationNTV\\Resources\\EmblemIcon.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addGap(86, 86, 86)
                .addComponent(jLabel2)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(22, 22, 22))
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 102));
        jPanel4.setForeground(new java.awt.Color(255, 204, 102));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setText("MINISTRY OF ROAD TRANSPORT & HIGHWAYS");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setText("VAHAN CITIZEN SERVICE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(705, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(856, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(20, 20, 20)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(21, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(1, 1, 1)))
        );

        NewUserLink.setBackground(new java.awt.Color(255, 255, 255));
        NewUserLink.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        NewUserLink.setText("Date of Expiry");
        NewUserLink.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NewUserLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewUserLinkMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        jLabel12.setText("Form 25");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel13.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel13.setText("Form of application for renewal of Certificate of Registration of a motor vehicle");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        RenewalSub.setBackground(new java.awt.Color(255, 204, 102));
        RenewalSub.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        RenewalSub.setForeground(new java.awt.Color(255, 204, 102));
        RenewalSub.setText("Submitted a form? Check submission status");
        RenewalSub.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        RenewalSub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RenewalSubMouseClicked(evt);
            }
        });

        Confirm.setForeground(new java.awt.Color(255, 204, 102));
        Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmActionPerformed(evt);
            }
        });

        NewUserLink2.setBackground(new java.awt.Color(255, 255, 255));
        NewUserLink2.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        NewUserLink2.setText("I hereby declare that the certificate of registration has not been cancelled by any registering authority");
        NewUserLink2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NewUserLink2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewUserLink2MouseClicked(evt);
            }
        });

        NewUserLink3.setBackground(new java.awt.Color(255, 255, 255));
        NewUserLink3.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        NewUserLink3.setText("Name of the applicant");
        NewUserLink3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NewUserLink3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewUserLink3MouseClicked(evt);
            }
        });

        NewUserLink4.setBackground(new java.awt.Color(255, 255, 255));
        NewUserLink4.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        NewUserLink4.setText("Registered Number");
        NewUserLink4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NewUserLink4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewUserLink4MouseClicked(evt);
            }
        });

        NewUserLink5.setBackground(new java.awt.Color(255, 255, 255));
        NewUserLink5.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        NewUserLink5.setText("Present Address");
        NewUserLink5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NewUserLink5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewUserLink5MouseClicked(evt);
            }
        });

        NewUserLink6.setBackground(new java.awt.Color(255, 255, 255));
        NewUserLink6.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        NewUserLink6.setText("Date of Issue");
        NewUserLink6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NewUserLink6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewUserLink6MouseClicked(evt);
            }
        });

        NewUserLink7.setBackground(new java.awt.Color(255, 255, 255));
        NewUserLink7.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        NewUserLink7.setText("Issuing Registering Authority");
        NewUserLink7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NewUserLink7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewUserLink7MouseClicked(evt);
            }
        });

        IssuingAuthority.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        IssuingAuthority.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        IssuingAuthority.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));

        Name.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        Name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));

        RegisterNo.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        RegisterNo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        RegisterNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));

        DateIssue.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        DateIssue.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        DateIssue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));

        DateExpiry.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        DateExpiry.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        DateExpiry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));

        Address.setColumns(20);
        Address.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        Address.setRows(5);
        Address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));
        jScrollPane1.setViewportView(Address);

        NextBtn.setBackground(new java.awt.Color(255, 204, 102));
        NextBtn.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        NextBtn.setText("NEXT ");
        NextBtn.setBorder(null);
        NextBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NextBtnMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabel14.setText("1. General Details");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        KM.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        KM.setIcon(new javax.swing.ImageIcon("E:\\E-Governance\\RegistrationNTV\\Resources\\KnowMore.png")); // NOI18N
        KM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KMMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Confirm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NewUserLink2, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(RenewalSub)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(NewUserLink7)
                                        .addComponent(NewUserLink5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(IssuingAuthority, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(115, 115, 115)
                                    .addComponent(KM)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NewUserLink4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NewUserLink6, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NewUserLink3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(DateIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(NewUserLink, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DateExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                                        .addComponent(RegisterNo, javax.swing.GroupLayout.Alignment.LEADING)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(238, 238, 238)
                .addComponent(jLabel12)
                .addGap(0, 481, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(KM)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewUserLink3))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterNo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewUserLink4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewUserLink6)
                    .addComponent(NewUserLink)
                    .addComponent(DateExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewUserLink7)
                    .addComponent(IssuingAuthority, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(NewUserLink5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewUserLink2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RenewalSub))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewUserLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserLinkMouseClicked
        // TODO add your handling code here:
        new NewUser().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NewUserLinkMouseClicked

    private void RenewalSubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RenewalSubMouseClicked
        // TODO add your handling code here:
        RenewalStatus R = new RenewalStatus();
        R.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RenewalSubMouseClicked

    private void ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmActionPerformed

    private void NewUserLink2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserLink2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NewUserLink2MouseClicked

    private void NewUserLink3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserLink3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NewUserLink3MouseClicked

    private void NewUserLink4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserLink4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NewUserLink4MouseClicked

    private void NewUserLink5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserLink5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NewUserLink5MouseClicked

    private void NewUserLink6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserLink6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NewUserLink6MouseClicked

    private void NewUserLink7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserLink7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NewUserLink7MouseClicked

    private void NextBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextBtnMouseClicked
        // TODO add your handling code here:
        
        //Storing the input in string
        String UserText = Name.getText();
        String RegNo = RegisterNo.getText();
        String DtIssue = DateIssue.getText();
        String DtExp = DateExpiry.getText();
        String RegAuth = IssuingAuthority.getText();
        String Addr = Address.getText();
        
      int result = validateVerify();
     if(result != -1) {
            JOptionPane.showMessageDialog(this, " Error Submitting the Request\n"+" "+verify[result]+" is mandatory \n"+"\n", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    else {
            UserHomeII U2 = new UserHomeII(UserText,RegNo,DtIssue,DtExp,RegAuth,Addr);
            U2.setVisible(true);
            this.dispose();
            }
    }//GEN-LAST:event_NextBtnMouseClicked

    private void KMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KMMouseClicked
        // TODO add your handling code here:
        KnowMoreI K = new KnowMoreI();
        K.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KMMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Address;
    private javax.swing.JCheckBox Confirm;
    private javax.swing.JTextField DateExpiry;
    private javax.swing.JTextField DateIssue;
    private javax.swing.JTextField IssuingAuthority;
    private javax.swing.JLabel KM;
    private javax.swing.JTextField Name;
    private javax.swing.JLabel NewUserLink;
    private javax.swing.JLabel NewUserLink2;
    private javax.swing.JLabel NewUserLink3;
    private javax.swing.JLabel NewUserLink4;
    private javax.swing.JLabel NewUserLink5;
    private javax.swing.JLabel NewUserLink6;
    private javax.swing.JLabel NewUserLink7;
    private javax.swing.JButton NextBtn;
    private javax.swing.JTextField RegisterNo;
    private javax.swing.JLabel RenewalSub;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
