/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registrationntv;

import javax.swing.JOptionPane;

/**
 *
 * @author gygsh
 */
public class UserHomeII extends javax.swing.JFrame {
    //Global Variable context
    String TName,TRegNo,TDateIssue,TDateExp,TAddr,TIssueAuth;
     String vehicleClass;
            String bodyType;
            String makerName;
            String doM;
            String cC ;
            String cyl;
            String Mclass;
            String engineNo;
            String seatingCap;
            String unladen;
            String fuel;
            String reciept;
            String fee;
    
    /**
     * Creates new form UserHomeII
     */
    String[] verify =  {"Class Of Vehicle","Type Of Body","Maker's Name","Date Of Manufacture","Cubic Capacity / Horse Power","Number Of Cylinders","Maker's Classification"
                        ,"Engine Number","Seating Capacity","Unladen Weight","Fuel Used","Payment Reciept Number","Payment Fees"};
    
    int verifyValidate() {
        int count = -1;
        if(VehicleClass.getText().equals("")) {
            count = 0;
            return count;
        }
        if(BodyType.getText().equals("")) {
             count = 1;
            return count;
        }
        if(MakerName.getText().equals("")) {
             count = 2;
            return count;
        }
        if(DoM.getText().equals("")) {
             count = 3;
            return count;
        }
        if(CC.getText().equals("")) {
             count = 4;
            return count;
        }
        if(NoOfCyl.getText().equals("")) {
             count = 5;
            return count;
        }
        if(MakersClassification.getText().equals("")) {
             count = 6;
            return count;
        }
        if(EngineNo.getText().equals("")) {
             count = 7;
            return count;
        }
        if(SeatingCapacity.getText().equals("")){
            count = 8;
            return count;
        }
        if(UnladenWeight.getText().equals("")) {
             count = 9;
            return count;
        }
        if(FuelUsed.getText().equals("")) {
             count = 10;
            return count;
        }
        if(PaymentNo.getText().equals("")) {
             count = 11;
            return count;
        }
        if(PaymentFee.getText().equals("")) {
             count = 12;
            return count;
        }
        
        if(count != -1) {
            return count;
        }
        return count;
    }
    public UserHomeII() {
        initComponents();
         setLocationRelativeTo(null);
    }
    
    public UserHomeII(String Name, String RegNo, String DateIssue, String DateExp, String RegAuth, String Addr) {
        initComponents();
        setLocationRelativeTo(null);
        TName = (Name);
        TRegNo = (RegNo);
        TDateIssue = (DateIssue);
        TDateExp = (DateExp);
        TIssueAuth = RegAuth;
        TAddr = (Addr);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        NewUserLink3 = new javax.swing.JLabel();
        VehicleClass = new javax.swing.JTextField();
        SubmitBtn = new javax.swing.JButton();
        NewUserLink8 = new javax.swing.JLabel();
        BodyType = new javax.swing.JTextField();
        NewUserLink9 = new javax.swing.JLabel();
        MakerName = new javax.swing.JTextField();
        QuestionOne = new javax.swing.JLabel();
        DoM = new javax.swing.JTextField();
        NewUserLink12 = new javax.swing.JLabel();
        NewUserLink11 = new javax.swing.JLabel();
        NewUserLink13 = new javax.swing.JLabel();
        CC = new javax.swing.JTextField();
        QuestionTwo = new javax.swing.JLabel();
        NewUserLink14 = new javax.swing.JLabel();
        NoOfCyl = new javax.swing.JTextField();
        MakersClassification = new javax.swing.JTextField();
        NewUserLink15 = new javax.swing.JLabel();
        EngineNo = new javax.swing.JTextField();
        NewUserLink16 = new javax.swing.JLabel();
        SeatingCapacity = new javax.swing.JTextField();
        NewUserLink17 = new javax.swing.JLabel();
        UnladenWeight = new javax.swing.JTextField();
        NewUserLink18 = new javax.swing.JLabel();
        FuelUsed = new javax.swing.JTextField();
        NewUserLink19 = new javax.swing.JLabel();
        PaymentFee = new javax.swing.JTextField();
        NewUserLink20 = new javax.swing.JLabel();
        PaymentNo = new javax.swing.JTextField();
        NewUserLink21 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));
        jPanel3.setForeground(new java.awt.Color(255, 204, 102));

        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        jLabel2.setText("RENEWAL OF NON - TRANSPORT VEHICLES");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\E-Governance\\RegistrationNTV\\Resources\\EmblemIcon.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addGap(86, 86, 86)
                .addComponent(jLabel2)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(22, 22, 22))
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 102));
        jPanel4.setForeground(new java.awt.Color(255, 204, 102));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setText("MINISTRY OF ROAD TRANSPORT & HIGHWAYS");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("VAHAN CITIZEN SERVICE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabel13.setText("3. Payment Details");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        NewUserLink3.setBackground(new java.awt.Color(255, 255, 255));
        NewUserLink3.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        NewUserLink3.setText("Class of Vehicle");
        NewUserLink3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NewUserLink3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewUserLink3MouseClicked(evt);
            }
        });

        VehicleClass.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        VehicleClass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        VehicleClass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));
        VehicleClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehicleClassActionPerformed(evt);
            }
        });

        SubmitBtn.setBackground(new java.awt.Color(255, 204, 102));
        SubmitBtn.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        SubmitBtn.setText("SUBMIT");
        SubmitBtn.setBorder(null);
        SubmitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitBtnMouseClicked(evt);
            }
        });

        NewUserLink8.setBackground(new java.awt.Color(255, 255, 255));
        NewUserLink8.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        NewUserLink8.setText("Type of Body");
        NewUserLink8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NewUserLink8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewUserLink8MouseClicked(evt);
            }
        });

        BodyType.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        BodyType.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        BodyType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));
        BodyType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BodyTypeActionPerformed(evt);
            }
        });

        NewUserLink9.setBackground(new java.awt.Color(255, 255, 255));
        NewUserLink9.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        NewUserLink9.setText("Maker's Name");
        NewUserLink9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NewUserLink9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewUserLink9MouseClicked(evt);
            }
        });

        MakerName.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        MakerName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        MakerName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));

        QuestionOne.setBackground(new java.awt.Color(255, 255, 255));
        QuestionOne.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        QuestionOne.setForeground(new java.awt.Color(255, 204, 102));
        QuestionOne.setText("?");
        QuestionOne.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        QuestionOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuestionOneMouseClicked(evt);
            }
        });

        DoM.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        DoM.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        DoM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));

        NewUserLink12.setBackground(new java.awt.Color(255, 255, 255));
        NewUserLink12.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        NewUserLink12.setText("Maker’s classification");
        NewUserLink12.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NewUserLink12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewUserLink12MouseClicked(evt);
            }
        });

        NewUserLink11.setBackground(new java.awt.Color(255, 255, 255));
        NewUserLink11.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        NewUserLink11.setText("DoM");
        NewUserLink11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NewUserLink11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewUserLink11MouseClicked(evt);
            }
        });

        NewUserLink13.setBackground(new java.awt.Color(255, 255, 255));
        NewUserLink13.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        NewUserLink13.setText("CC/Hp");
        NewUserLink13.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NewUserLink13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewUserLink13MouseClicked(evt);
            }
        });

        CC.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        CC.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        CC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));

        QuestionTwo.setBackground(new java.awt.Color(255, 255, 255));
        QuestionTwo.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        QuestionTwo.setForeground(new java.awt.Color(255, 204, 102));
        QuestionTwo.setText("?");
        QuestionTwo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        QuestionTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuestionTwoMouseClicked(evt);
            }
        });

        NewUserLink14.setBackground(new java.awt.Color(255, 255, 255));
        NewUserLink14.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        NewUserLink14.setText("No of Cylinders");
        NewUserLink14.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NewUserLink14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewUserLink14MouseClicked(evt);
            }
        });

        NoOfCyl.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        NoOfCyl.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        NoOfCyl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));

        MakersClassification.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        MakersClassification.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        MakersClassification.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));

        NewUserLink15.setBackground(new java.awt.Color(255, 255, 255));
        NewUserLink15.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        NewUserLink15.setText("Engine No");
        NewUserLink15.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NewUserLink15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewUserLink15MouseClicked(evt);
            }
        });

        EngineNo.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        EngineNo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        EngineNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));

        NewUserLink16.setBackground(new java.awt.Color(255, 255, 255));
        NewUserLink16.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        NewUserLink16.setText("Seating Capacity");
        NewUserLink16.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NewUserLink16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewUserLink16MouseClicked(evt);
            }
        });

        SeatingCapacity.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        SeatingCapacity.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        SeatingCapacity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));

        NewUserLink17.setBackground(new java.awt.Color(255, 255, 255));
        NewUserLink17.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        NewUserLink17.setText("Unladen Weight");
        NewUserLink17.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NewUserLink17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewUserLink17MouseClicked(evt);
            }
        });

        UnladenWeight.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        UnladenWeight.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        UnladenWeight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));

        NewUserLink18.setBackground(new java.awt.Color(255, 255, 255));
        NewUserLink18.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        NewUserLink18.setText("Fuel Used");
        NewUserLink18.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NewUserLink18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewUserLink18MouseClicked(evt);
            }
        });

        FuelUsed.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        FuelUsed.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        FuelUsed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));

        NewUserLink19.setBackground(new java.awt.Color(255, 255, 255));
        NewUserLink19.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        NewUserLink19.setText("₹");
        NewUserLink19.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NewUserLink19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewUserLink19MouseClicked(evt);
            }
        });

        PaymentFee.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        PaymentFee.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        PaymentFee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));

        NewUserLink20.setBackground(new java.awt.Color(255, 255, 255));
        NewUserLink20.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        NewUserLink20.setText("Payment recipt No");
        NewUserLink20.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NewUserLink20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewUserLink20MouseClicked(evt);
            }
        });

        PaymentNo.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        PaymentNo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        PaymentNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));

        NewUserLink21.setBackground(new java.awt.Color(255, 255, 255));
        NewUserLink21.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        NewUserLink21.setText("Payment Fee  ");
        NewUserLink21.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NewUserLink21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewUserLink21MouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabel14.setText("2. Vehicle Details");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(NewUserLink20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(PaymentNo, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(NewUserLink3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(NewUserLink12))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(NewUserLink15)
                                                    .addGap(104, 104, 104)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(NewUserLink16)
                                                .addGap(50, 50, 50)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(EngineNo)
                                            .addComponent(MakersClassification, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SeatingCapacity, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(VehicleClass, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(DoM, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(NewUserLink8)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(BodyType, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(NewUserLink13)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(QuestionTwo)
                                                        .addGap(270, 270, 270))))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(NewUserLink17)
                                        .addGap(50, 50, 50)
                                        .addComponent(UnladenWeight))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(NewUserLink18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(FuelUsed, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(NewUserLink11)
                                        .addGap(18, 18, 18)
                                        .addComponent(QuestionOne)
                                        .addGap(485, 485, 485)
                                        .addComponent(CC, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(NewUserLink21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(NewUserLink19)
                                        .addGap(18, 18, 18)
                                        .addComponent(PaymentFee, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(NewUserLink14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(NoOfCyl, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(NewUserLink9)
                                        .addGap(30, 30, 30)
                                        .addComponent(MakerName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewUserLink3)
                    .addComponent(VehicleClass, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewUserLink8)
                    .addComponent(BodyType, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewUserLink9)
                    .addComponent(MakerName, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoM, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuestionOne)
                    .addComponent(NewUserLink11)
                    .addComponent(CC, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewUserLink13)
                    .addComponent(QuestionTwo)
                    .addComponent(NoOfCyl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewUserLink14))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewUserLink12)
                    .addComponent(MakersClassification, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewUserLink15)
                    .addComponent(EngineNo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SeatingCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewUserLink16))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnladenWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewUserLink17))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FuelUsed, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewUserLink18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PaymentNo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewUserLink20))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PaymentFee, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewUserLink19)
                            .addComponent(NewUserLink21))
                        .addGap(26, 26, 26)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewUserLink3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserLink3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NewUserLink3MouseClicked

    private void SubmitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitBtnMouseClicked
        // TODO add your handling code here:
        int result = verifyValidate();
        if(verifyValidate() == -1){
             vehicleClass = VehicleClass.getText();
             bodyType = BodyType.getText();
             makerName = MakerName.getText();
             doM = DoM.getText();
             cC = CC.getText();
             cyl = NoOfCyl.getText();
             Mclass = MakersClassification.getText();
             engineNo = EngineNo.getText();
             seatingCap = SeatingCapacity.getText();
             unladen = UnladenWeight.getText();
             fuel = FuelUsed.getText();
             reciept = PaymentNo.getText();
             fee = PaymentFee.getText();
            
                    
            UserHomeIII U3 = new UserHomeIII(TName,TRegNo,TDateIssue,TDateExp,TIssueAuth,TAddr,
                                            vehicleClass,bodyType,makerName,doM,cC,Mclass,
                                           engineNo,seatingCap,unladen,fuel,reciept,fee);
            U3.setVisible(true);
            this.dispose();
        }
        
       
            
        else {
             JOptionPane.showMessageDialog(this, " Error Submitting the Request\n"+" "+verify[result]+" is mandatory \n"+"\n", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
       
    }//GEN-LAST:event_SubmitBtnMouseClicked

    private void NewUserLink8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserLink8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NewUserLink8MouseClicked

    private void NewUserLink9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserLink9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NewUserLink9MouseClicked

    private void QuestionOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuestionOneMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, " Enter the Date Of Manufacturing \n","QUERY",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_QuestionOneMouseClicked

    private void NewUserLink12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserLink12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NewUserLink12MouseClicked

    private void NewUserLink11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserLink11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NewUserLink11MouseClicked

    private void NewUserLink13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserLink13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NewUserLink13MouseClicked

    private void QuestionTwoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuestionTwoMouseClicked
        // TODO add your handling code here:
                JOptionPane.showMessageDialog(this, " Enter the Cubic Capacity [or] Horse Power \n Of the vehicle \n","QUERY",JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_QuestionTwoMouseClicked

    private void NewUserLink14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserLink14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NewUserLink14MouseClicked

    private void NewUserLink15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserLink15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NewUserLink15MouseClicked

    private void NewUserLink16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserLink16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NewUserLink16MouseClicked

    private void NewUserLink17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserLink17MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NewUserLink17MouseClicked

    private void NewUserLink18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserLink18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NewUserLink18MouseClicked

    private void NewUserLink19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserLink19MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NewUserLink19MouseClicked

    private void NewUserLink20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserLink20MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NewUserLink20MouseClicked

    private void NewUserLink21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserLink21MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NewUserLink21MouseClicked

    private void BodyTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BodyTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BodyTypeActionPerformed

    private void VehicleClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehicleClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VehicleClassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserHomeII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserHomeII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserHomeII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserHomeII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserHomeII().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BodyType;
    private javax.swing.JTextField CC;
    private javax.swing.JTextField DoM;
    private javax.swing.JTextField EngineNo;
    private javax.swing.JTextField FuelUsed;
    private javax.swing.JTextField MakerName;
    private javax.swing.JTextField MakersClassification;
    private javax.swing.JLabel NewUserLink11;
    private javax.swing.JLabel NewUserLink12;
    private javax.swing.JLabel NewUserLink13;
    private javax.swing.JLabel NewUserLink14;
    private javax.swing.JLabel NewUserLink15;
    private javax.swing.JLabel NewUserLink16;
    private javax.swing.JLabel NewUserLink17;
    private javax.swing.JLabel NewUserLink18;
    private javax.swing.JLabel NewUserLink19;
    private javax.swing.JLabel NewUserLink20;
    private javax.swing.JLabel NewUserLink21;
    private javax.swing.JLabel NewUserLink3;
    private javax.swing.JLabel NewUserLink8;
    private javax.swing.JLabel NewUserLink9;
    private javax.swing.JTextField NoOfCyl;
    private javax.swing.JTextField PaymentFee;
    private javax.swing.JTextField PaymentNo;
    private javax.swing.JLabel QuestionOne;
    private javax.swing.JLabel QuestionTwo;
    private javax.swing.JTextField SeatingCapacity;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JTextField UnladenWeight;
    private javax.swing.JTextField VehicleClass;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
