/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registrationntv;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author gygsh
 */
public class UserHomeIII extends javax.swing.JFrame {

    /**
     * Creates new form UserHomeIII
     */
    
    String[] verify = {"Registration Certificate Number","Insurance Certificate Number","Emission Certificate Number","Tax Certificate Number"};
    int verifyValidate() {
        int count = -1;
        if(Registration.getText().equals("")) {
            count = 0;
            return count;
        }
        if(Insurance.getText().equals("")) {
            count = 1;
            return count;
        }
        if(Emission.getText().equals("")) {
            count = 2;
            return count;
        }
        if(Tax.getText().equals("")) {
            count = 3;
            return count;
        }
       
        if(count != 0) {
            return count;
         }
        
         return count;
    }
    public UserHomeIII() {
        initComponents();
       setLocationRelativeTo(null);
    }
    String FTName;
    String FTRegNo;
    String FTDateIssue;
    String FTDateExp;
    String FTIssueAuth;
    String FTAddr;
    String FvehicleClass;
    String FbodyType;
    String FmakerName;
    String FdoM;
    String FcC;
    String FMclass;
    String FengineNo;
    String FseatingCap;
    String Funladen;
    String Ffuel;
    String Freciept;
    String Ffee;
    String status = "W";
    String RenewalNo;
    String RC,IC,EC,TC;
                                           
    
       public UserHomeIII(String TName,String TRegNo,String TDateIssue,String TDateExp,String TIssueAuth,
                           String TAddr,String vehicleClass,String bodyType,String makerName,String doM,String cC,String Mclass,
                                           String engineNo,String seatingCap,String unladen,String fuel,String reciept,String fee) {
           initComponents();
           setLocationRelativeTo(null);
           
     FTName = TName;
     FTRegNo = TRegNo;
     FTDateIssue = TDateIssue;
     FTDateExp = TDateExp;
     FTIssueAuth = TIssueAuth;
     FTAddr = TAddr;
     FvehicleClass = vehicleClass;
     FbodyType = bodyType;
     FmakerName = makerName;
     FdoM = doM;
     FcC = cC;
     FMclass = Mclass;
     FengineNo = engineNo;
     FseatingCap = seatingCap;
     Funladen = unladen;
     Ffuel = fuel;
     Freciept = reciept;
     Ffee = fee;
           
           
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NewUserLink3 = new javax.swing.JLabel();
        NewUserLink4 = new javax.swing.JLabel();
        Registration = new javax.swing.JTextField();
        Insurance = new javax.swing.JTextField();
        SubmitBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        NewUserLink5 = new javax.swing.JLabel();
        NewUserLink6 = new javax.swing.JLabel();
        Emission = new javax.swing.JTextField();
        Tax = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));
        jPanel3.setForeground(new java.awt.Color(255, 204, 102));

        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        jLabel2.setText("RENEWAL OF NON - TRANSPORT VEHICLES");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\E-Governance\\RegistrationNTV\\Resources\\EmblemIcon.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addGap(86, 86, 86)
                .addComponent(jLabel2)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(22, 22, 22))
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 102));
        jPanel4.setForeground(new java.awt.Color(255, 204, 102));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setText("MINISTRY OF ROAD TRANSPORT & HIGHWAYS");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("VAHAN CITIZEN SERVICE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NewUserLink3.setBackground(new java.awt.Color(255, 255, 255));
        NewUserLink3.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        NewUserLink3.setText("Registration Certificate");
        NewUserLink3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NewUserLink3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewUserLink3MouseClicked(evt);
            }
        });

        NewUserLink4.setBackground(new java.awt.Color(255, 255, 255));
        NewUserLink4.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        NewUserLink4.setText("Insurance Certificate");
        NewUserLink4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NewUserLink4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewUserLink4MouseClicked(evt);
            }
        });

        Registration.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        Registration.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Registration.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));

        Insurance.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        Insurance.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Insurance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));

        SubmitBtn.setBackground(new java.awt.Color(255, 204, 102));
        SubmitBtn.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        SubmitBtn.setText("NEXT ");
        SubmitBtn.setBorder(null);
        SubmitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitBtnMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabel14.setText("4. Required Documents");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        NewUserLink5.setBackground(new java.awt.Color(255, 255, 255));
        NewUserLink5.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        NewUserLink5.setText("Emission Certificate");
        NewUserLink5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NewUserLink5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewUserLink5MouseClicked(evt);
            }
        });

        NewUserLink6.setBackground(new java.awt.Color(255, 255, 255));
        NewUserLink6.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        NewUserLink6.setText("Tax certificate ");
        NewUserLink6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NewUserLink6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewUserLink6MouseClicked(evt);
            }
        });

        Emission.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        Emission.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Emission.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));

        Tax.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        Tax.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Tax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));

        jLabel15.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel15.setText("Submit the certificate numbers of the following documents");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        Home.setIcon(new javax.swing.ImageIcon("E:\\E-Governance\\RegistrationNTV\\Resources\\HomeIcon.png")); // NOI18N
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NewUserLink6, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NewUserLink5, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Emission, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NewUserLink4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NewUserLink3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Registration, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                                    .addComponent(Insurance, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addContainerGap(418, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Home)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel14)
                .addGap(38, 38, 38)
                .addComponent(jLabel15)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewUserLink3)
                    .addComponent(Registration, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Insurance, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewUserLink4))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Emission, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewUserLink5))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tax, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewUserLink6))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Home)
                        .addGap(77, 77, 77))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewUserLink3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserLink3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NewUserLink3MouseClicked

    private void NewUserLink4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserLink4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NewUserLink4MouseClicked

    private void SubmitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitBtnMouseClicked
        // TODO add your handling code here:

        //Storing the input in str
        
        int res = verifyValidate();

        if(res == -1) {
            RC = Registration.getText();
            TC = Tax.getText();
            IC = Insurance.getText();
            EC = Emission.getText();
            RenewalNo = "RR"+"0000"+FTRegNo.toUpperCase();
             
                       
         try {
            String url = "jdbc:h2:~/test";
            Connection C = DriverManager.getConnection(url,"sa","sa");
            String query = "INSERT INTO NTVMAIN VALUES ("+
                    "'"+RenewalNo+"',"+
                     "'"+FTRegNo+"',"+
                   "'"+FTDateIssue+"',"+
                    "'"+FTDateExp +"',"+
                    "'"+FTIssueAuth +"',"+
                    "'"+FTAddr +"',"+
                    "'"+FvehicleClass +"',"+
                    "'"+FbodyType +"',"+
                    "'"+FmakerName +"',"+
                    "'"+FdoM  +"',"+
                    "'"+FcC  +"',"+
                    "'"+FMclass  +"',"+
                    "'"+FengineNo  +"',"+ 
                    "'"+FseatingCap +"',"+
                    "'"+Funladen +"',"+
                    "'"+Ffuel +"',"+
                    "'"+Freciept +"',"+
                    "'"+Ffee +"',"+
                    "'"+RC +"',"+
                    "'"+IC +"',"+
                    "'"+EC +"',"+
                    "'"+TC +"',"+
                    "'"+status +"'"+
                     ");";
         
            System.out.println(query);
            Statement S = C.createStatement();
            S.executeUpdate(query);
           
                    
            C.close();
            S.close();
            
             UserHomeFinal U1 = new UserHomeFinal(RenewalNo);
             U1.setVisible(true);
            this.dispose();
            
        } catch (SQLException E) {System.out.println(E);
         showMessageDialog(this,"Error Registering \n Contact System Admininstrator","ALERT",JOptionPane.ERROR_MESSAGE);}
                 
        }
        else {
                        JOptionPane.showMessageDialog(this, " Error Submitting the Request\n"+" "+verify[res]+" is mandatory \n"+"\n", "ERROR", JOptionPane.ERROR_MESSAGE);
 
        }
     
    }//GEN-LAST:event_SubmitBtnMouseClicked

    private void NewUserLink5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserLink5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NewUserLink5MouseClicked

    private void NewUserLink6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserLink6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NewUserLink6MouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        // TODO add your handling code here:
        new BootPanel().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserHomeIII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserHomeIII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserHomeIII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserHomeIII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserHomeIII().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Emission;
    private javax.swing.JLabel Home;
    private javax.swing.JTextField Insurance;
    private javax.swing.JLabel NewUserLink3;
    private javax.swing.JLabel NewUserLink4;
    private javax.swing.JLabel NewUserLink5;
    private javax.swing.JLabel NewUserLink6;
    private javax.swing.JTextField Registration;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JTextField Tax;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
